version: 0.1

phases:
  build:
    commands:
      - echo Build completed on `date`
      - mvn compile

  post_build:
    commands:
      - mvn package
      - mkdir artifact
      - unzip target/SampleMavenTomcatApp.war -d artifact/
      - mv artifact/WEB-INF WEB-INF
artifacts:
  files:
   - WEB-INF/**/*
  name: artifact 
